Bingo card
selasdev/bingo-socket-io pull request #2
Opened 2023-04-09 20:55 UTC by jefferson10147

Se hicieron cambios en el lado del servidor para resolver los inconvenientes encontrados al momento usar la clase Map. 

Se creó el componente Card para generar un tablero, este hace uso del backend para:
- Generar un tablero de manera aleatoria y regenerarlo si el usuario quiere.
- Una vez empezado el juego marca el número emitido en el tablero (si este está en el tablero). Y muestra el último número generado así no esté marcado.
- Se implementó un indicador en el cartón para indicar si el usuario está conectado o desconectado.
- Se creó la opción para que  el usuario pueda cantar "BINGO", aunque la función de verificación del servidor no parece estar haciendo toda la verificación.

Se conectó la vista de ingresar usuario con la de generar el cartón.

2023-04-09 20:59 UTC, jefferson10147 commented on backend/server/bingoServer.js
> -const { setInterval } = require("timers/promises");
Se elimina esta linea para usar la función setInterval nativa del navegador.

2023-04-09 21:01 UTC, jefferson10147 commented on backend/server/bingoServer.js
> -    this.gameState.players[newPlayer.id] = newPlayer;
Ahora esta asignación se hace dentro de la función "sendTable" con el fin de poder regenerar tableros para un jugador en especifico. Por favor revisar la función "sendTable" para revisar a qué me refiero.

2023-04-09 21:01 UTC, jefferson10147 commented on backend/server/bingoServer.js
> +    this.sendTable(socket, newPlayer);
Se envía el objeto "newPlayer" para poder realizar la asignación dentro de "sendTable".

2023-04-09 21:01 UTC, jefferson10147 commented on backend/server/bingoServer.js
> +    const player = this.gameState.players.get(socket.id);
Se utiliza el método "get" propio de la clase Map.

2023-04-09 21:02 UTC, jefferson10147 commented on backend/server/bingoServer.js
> +    const player = newPlayer ? newPlayer : this.gameState.players.get(socket.id);
Verifca si el jugador es nuevo o ya existe, a partir de ahí se le asigna un nuevo tablero o no (según la clase map).

2023-04-09 21:03 UTC, jefferson10147 commented on backend/server/bingoServer.js
> +    const playersMapWithoutTargetPlayer = arrayOfPlayersFiltered.filter(
La función filter no existe en la clase Ma, por lo que fue necesaria esta implementación.

2023-04-09 21:04 UTC, jefferson10147 commented on frontend/src/app/page.js
> +        "Esperando confirmación de tabla"} */}
Este mensaje se maneja en la tarjeta del bingo.

2023-04-09 21:06 UTC, jefferson10147 commented on frontend/src/app/views/Card/index.js
> +            socket.emit(clientEvents.changeGameMode, { mode: "FULL" });
Se emite el evento de inicio de juego cada vez que se une, pero esta manera se puede cambiar dependiendo de como vayamos a definir que el juego se inicia.

2023-04-09 21:51 UTC, selasdev commented
Gracias! Voy a echarle un ojo a todo en un rato

2023-04-10 16:32 UTC, eagskunst requested changes

2023-04-10 16:32 UTC, eagskunst commented on backend/server/bingoServer.js
> +    const playersMapWithoutTargetPlayer = arrayOfPlayersFiltered.filter(
En vez de `arrayOfPlayersFiltered`, debería ser `arrayOfPlayers` o solo `players`, ya que no se está filtrando

2023-04-10 16:32 UTC, eagskunst commented on backend/server/bingoServer.js
> +   * @param {} newPlayer
Actualizar la documentación de la función con el nuevo parámetro y la nueva lógica 🙏

2023-04-10 16:32 UTC, eagskunst commented on frontend/src/app/views/Card/index.js
> +    const [isLoading, setIsLoading] = useState(true);
@selasdev tener los estados dispersos está bien? no sé si sea mejor encapsular las variables de carga (isLoading, loadingMessage) en una clase/función de estado 🤔. No sé como sea el estándar en React

2023-04-11 01:32 UTC, selasdev commented on frontend/src/app/views/Card/index.js
> +            socket.emit(clientEvents.changeGameMode, { mode: "FULL" });
Jajaja esto es raro pero supongo que tendrá que ser así por ahora. Podemos dejar que cada usuario también cambie el modo de juego como para "demostrar" la funcionalidad cuando lo presentemos, sin embargo en una partida normal no tendría sentido.

2023-04-11 01:36 UTC, selasdev commented
En general, las cosas se ven bien y funcionan! Está muy bien explicado el código mediante los comentarios, muchas gracias @jefferson10147.

Tengo la duda ahora acá jajaja, actualmente está funcionando el juego completo? El juego inicia cuando hay más de dos jugadores conectados o cómo es esa lógica ahora? 🤔 

También que pasa al terminar el juego? se reinicia todo? jajajaja

2023-04-11 02:19 UTC, eagskunst approved these changes
Lo dejó igual listo para que lo mergeen, gracias mano @jefferson10147

2023-04-15 21:43 UTC, jefferson10147 commented on frontend/src/app/views/Card/index.js
> +    const [isLoading, setIsLoading] = useState(true);
@eagskunst Este estado solo muestra un spinner de carga para no mostrar un tablero vacío.

2023-04-15 21:51 UTC, jefferson10147 commented on frontend/src/app/views/Card/index.js
> +            socket.emit(clientEvents.changeGameMode, { mode: "FULL" });
> da ahora acá jajaja, actualmente está funcionando el juego completo? El juego inicia cuando hay más de dos jugadores conectados o có

@selasdev El juego si está funcionando :)  por ahora se inicia la partida cuando se unen dos jugadores. 
Cuando inicia, todo funciona bien excepto al momento de verificar si alguien ha ganado. La función que se encarga de entregar los números cada cierto tiempo no está actualizando los tableros de los jugadores en el Backend, por lo tanto al llamar la verificación del ganador (que se hace cada vez que se genera un número) no sirve, pero en el front ya se hace esta llamada.

2023-04-16 14:33 UTC, selasdev approved these changes

2023-04-16 14:33 UTC, selasdev commented on frontend/src/app/views/Card/index.js
> +    const [isLoading, setIsLoading] = useState(true);
hmmmm, en casos comotal, lo ideal sería hacer un custom hook, que en vez de retornar una dupla retorne un set de datos..

`const { loading, setLoading, loadingMessage } = useLoading();`

Pero acá en este oportunidad lo que veo es es que tendría que ser un poco diferente debido a cómo está planteado, ya que este `loadingMessage` se usa no sólo para comunicar que está cargando si no también para comunicar si el usuario ha ganado o si no ha ganado.

El verdadero problema yace en que no estamos separando los componentes atómicamente!

Acá yo propondría separar esto en varios componentes @jefferson10147 

1. Un componente para renderizar la tarjeta de Bingo individualmente
-Tendría que ser atómico, recibir en sí el array de números y el de tachados.
2. Un componente para la vista de seleccionar el cartón, este reutilizaría el átomo de la tarjeta de Bingo para renderizarla, botones para aceptar  rechazar
3. Un componente para la partida, permitiría al usuario cantar la victoria y adicionalmente podría usar otros componentes cómo alguno para mostrar la lista de usuarios.

De la forma de arriba, podemos encapsular varios estados de forma diferente y hasta quizás también deshacernos de algunos.

2023-04-16 14:33 UTC, selasdev commented on frontend/src/app/views/Card/index.js
> +    return (
Todo esto queda medio spaghetti debido a lo de arriba 😢 

Hacer los cambios para un mejor código diría que es secundario pero es buena práctica tratar de hacerlo

2023-04-16 14:34 UTC, merged